--Exercise 1

SELECT DISTINCT country_code
FROM ACTOR_E
ORDER BY country_code;

--Exercise 2

SELECT MOVIE_CODE, TITLE
FROM MOVIE
WHERE YEAR < 1970 AND BOOK_CODE IS NULL;

--Exercise 3

SELECT ACT_CODE, NAME
FROM ACTOR_E
WHERE NAME LIKE '%John%';

--Exercise 4

SELECT MOVIE_CODE, TITLE
FROM MOVIE
WHERE LENGTH > 120 AND YEAR >= 1980 AND YEAR <= 1989;

--Exercise 5

SELECT MOVIE_CODE, TITLE
FROM MOVIE
WHERE BOOK_CODE IS NOT NULL AND DIRECTOR LIKE '%Pakula';

--Exercise 6

SELECT COUNT(*)
FROM MOVIE
WHERE LENGTH > 120 AND YEAR BETWEEN 1980 AND 1989;

--Exercise 7

SELECT COUNT(DISTINCT MOVIE_CODE)
FROM CLASSIFICATION
WHERE GEN_CODE IN ('BB5', 'GG4', 'JH6');

--Exercise 8

SELECT MIN(YEAR)
FROM BOOK_MOVIE;

--Exercise 9

SELECT AVG(LENGTH)
FROM MOVIE
WHERE YEAR = 1987;

--Exercise 10

SELECT SUM(LENGTH)
FROM MOVIE
WHERE DIRECTOR LIKE 'Steven Spielberg';

--Exercise 11

SELECT DISTINCT M.MOVIE_CODE, M.TITLE
FROM MOVIE M
JOIN PERFORMS P ON P.MOVIE_CODE = M.MOVIE_CODE
JOIN ACTOR_E A  ON A.ACT_CODE   = P.ACT_CODE
WHERE A.NAME = M.DIRECTOR
ORDER BY M.TITLE;

--Exercise 12

SELECT M.MOVIE_CODE, M.TITLE
FROM MOVIE M
JOIN CLASSIFICATION C ON C.MOVIE_CODE = M.MOVIE_CODE
JOIN GENRE G ON G.GEN_CODE = C.GEN_CODE
WHERE G.NAME = 'Comedia'
ORDER BY M.TITLE;

--Exercise 13

SELECT M.MOVIE_CODE, M.TITLE
FROM MOVIE M
JOIN BOOK_MOVIE B ON B.BOOK_CODE = M.BOOK_CODE
WHERE B.YEAR < 1950
ORDER BY M.TITLE;

--Exercise 14

SELECT DISTINCT C.COUNTRY_CODE, C.NAME
FROM COUNTRY C
JOIN ACTOR_E A ON A.COUNTRY_CODE = C.COUNTRY_CODE
JOIN PERFORMS P ON P.ACT_CODE = A.ACT_CODE
JOIN MOVIE M ON M.MOVIE_CODE = P.MOVIE_CODE
JOIN CLASSIFICATION CL ON CL.MOVIE_CODE = M.MOVIE_CODE
JOIN GENRE G ON G.GEN_CODE = CL.GEN_CODE
WHERE G.NAME = 'Comedia'
ORDER BY C.NAME;

-- Another way to write Exercise 14

SELECT DISTINCT C.COUNTRY_CODE, C.NAME
FROM COUNTRY C
JOIN ACTOR_E A ON A.COUNTRY_CODE = C.COUNTRY_CODE
JOIN PERFORMS P ON P.ACT_CODE = A.ACT_CODE
JOIN CLASSIFICATION CL ON CL.MOVIE_CODE = P.MOVIE_CODE
JOIN GENRE G ON G.GEN_CODE = CL.GEN_CODE
WHERE G.NAME = 'Comedia'
ORDER BY C.NAME;

--Exercise 15

SELECT M.MOVIE_CODE, M.TITLE
FROM MOVIE M
WHERE M.MOVIE_CODE IN (SELECT P.MOVIE_CODE
                       FROM PERFORMS P
                       WHERE P.ACT_CODE IN (SELECT A.ACT_CODE
                                            FROM ACTOR_E A
                                            WHERE A.NAME = M.DIRECTOR))
ORDER BY M.TITLE;

SELECT M.MOVIE_CODE, M.TITLE
FROM MOVIE M
WHERE M.MOVIE_CODE IN (
    SELECT C.MOVIE_CODE
    FROM CLASSIFICATION C
    WHERE C.GEN_CODE IN (
        SELECT G.GEN_CODE
        FROM GENRE G
        WHERE G.NAME = 'Comedia'
    )
)
ORDER BY M.TITLE;

SELECT M.MOVIE_CODE, M.TITLE
FROM MOVIE M
WHERE M.BOOK_CODE IN (
    SELECT B.BOOK_CODE
    FROM BOOK_MOVIE B
    WHERE B.YEAR < 1950
)
ORDER BY M.TITLE;

SELECT DISTINCT C.COUNTRY_CODE, C.NAME
FROM COUNTRY C
WHERE C.COUNTRY_CODE IN (
    SELECT A.COUNTRY_CODE
    FROM ACTOR_E A
    WHERE A.ACT_CODE IN (
        SELECT P.ACT_CODE
        FROM PERFORMS P
        WHERE P.MOVIE_CODE IN (
            SELECT M.MOVIE_CODE
            FROM MOVIE M
            WHERE M.MOVIE_CODE IN (
                SELECT CL.MOVIE_CODE
                FROM CLASSIFICATION CL
                WHERE CL.GEN_CODE IN (
                    SELECT G.GEN_CODE
                    FROM GENRE G
                    WHERE G.NAME = 'Comedia'
                )
            )
        )
    )
)
ORDER BY C.NAME;

--Exercise 16

SELECT DISTINCT A.ACT_CODE, A.NAME
FROM ACTOR_E A
JOIN PERFORMS P ON P.ACT_CODE = A.ACT_CODE
WHERE P.ROLE = 'Principal' AND EXTRACT(YEAR FROM A.BIRTH_DATE) < 1950
ORDER BY A.NAME;

--Exercise 17

SELECT B.BOOK_CODE, B.TITLE, B.AUTHOR
FROM BOOK_MOVIE B
JOIN MOVIE M ON M.BOOK_CODE = B.BOOK_CODE
WHERE M.YEAR BETWEEN 1990 AND 1999
ORDER BY B.TITLE;

--Exercise 18

SELECT B.BOOK_CODE, B.TITLE, B.AUTHOR
FROM BOOK_MOVIE B
WHERE B.BOOK_CODE NOT IN(SELECT M.BOOK_CODE
                        FROM MOVIE M
                        WHERE M.BOOK_CODE IS NOT NULL)
ORDER BY B.TITLE;

--Exercise 19

SELECT DISTINCT G.NAME
FROM GENRE G
JOIN CLASSIFICATION C ON C.GEN_CODE = G.GEN_CODE
WHERE NOT EXISTS (
    SELECT 1
    FROM PERFORMS P
    WHERE P.MOVIE_CODE = C.MOVIE_CODE
)
ORDER BY G.NAME;

--Exercise 20

-- Books that are used by some movie that has NO actors from USA
SELECT DISTINCT b.title            -- if your column is NAME, change to b.name
FROM book_movie b
JOIN movie m
  ON m.book_code = b.book_code
WHERE NOT EXISTS (                 -- there is no USA actor in that movie
    SELECT 1
    FROM performs p
    JOIN actor_e a  ON a.act_code = p.act_code
    JOIN country co ON co.country_code = a.country_code
    WHERE p.movie_code = m.movie_code
      AND UPPER(co.name) = 'USA'
)
ORDER BY b.title;                  -- or ORDER BY 1

--Exercise 21

SELECT COUNT(*)
FROM (
  SELECT DISTINCT m.movie_code
  FROM movie m
  JOIN classification c ON c.movie_code = m.movie_code
  JOIN genre g ON g.gen_code = c.gen_code
  WHERE g.name = 'Comedia'
    AND 1 = (
      SELECT COUNT(*)                -- exactly one actor in that role
      FROM performs p
      WHERE p.movie_code = m.movie_code
      AND p.role = 'Secundario'
    )
);

--Exercise 22

SELECT MIN(M.YEAR)
FROM MOVIE M 
JOIN PERFORMS P ON P.MOVIE_CODE = M.MOVIE_CODE
JOIN ACTOR_E A ON A.ACT_CODE = P.ACT_CODE
WHERE A.NAME = 'Jude Law' AND P.ROLE = 'Principal';

--Exercise 23

SELECT A.ACT_CODE, A.NAME
FROM ACTOR_E A 
WHERE A.BIRTH_DATE = (SELECT MIN(A1.BIRTH_DATE)
                      FROM ACTOR_E A1);

--Exercise 24

SELECT A1.ACT_CODE, A1.NAME, A1.BIRTH_DATE
FROM ACTOR_E A1
WHERE A1.BIRTH_DATE = ( 
  SELECT MIN(A2.BIRTH_DATE)
  FROM ACTOR_E A2
  WHERE EXTRACT(YEAR FROM A2.BIRTH_DATE) = 1940
);

--Exercise 25

SELECT G.NAME
FROM GENRE G
JOIN CLASSIFICATION C ON G.GEN_CODE = C.GEN_CODE
JOIN MOVIE M         ON M.MOVIE_CODE = C.MOVIE_CODE
WHERE M.LENGTH = (SELECT MAX(M1.LENGTH) FROM MOVIE M1)
ORDER BY G.NAME;

--Exercise 26

SELECT B.BOOK_CODE, B.TITLE
FROM BOOK_MOVIE B
JOIN MOVIE M ON M.BOOK_CODE = B.BOOK_CODE
JOIN PERFORMS P ON P.MOVIE_CODE = M.MOVIE_CODE
JOIN ACTOR_E A ON A.ACT_CODE = P.ACT_CODE
JOIN COUNTRY C ON C.COUNTRY_CODE = A.COUNTRY_CODE
WHERE C.NAME = 'España'
ORDER BY B.TITLE;

--Exercise 27

SELECT M.TITLE
FROM MOVIE M
WHERE M.YEAR < 1950
  AND (
    SELECT COUNT(DISTINCT C.GEN_CODE)
    FROM CLASSIFICATION C
    WHERE C.MOVIE_CODE = M.MOVIE_CODE
  ) > 1
ORDER BY M.TITLE;

--Exercise 28

SELECT COUNT(*)
FROM MOVIE M
WHERE (SELECT COUNT(*)
      FROM PERFORMS P
      WHERE P.MOVIE_CODE = M.MOVIE_CODE) < 4;

--Exercise 29

SELECT DISTINCT M.DIRECTOR
FROM MOVIE M
WHERE (SELECT SUM(M1.LENGTH)
       FROM MOVIE M1
       WHERE M1.DIRECTOR = M.DIRECTOR) > 250;

--Exercise 30

SELECT EXTRACT(YEAR FROM A.BIRTH_DATE) AS YEAR
FROM ACTOR_E A
GROUP BY EXTRACT(YEAR FROM A.BIRTH_DATE)
HAVING COUNT(*) > 3;

--Exercise 31

SELECT A.ACT_CODE, A.NAME
FROM ACTOR_E A
JOIN PERFORMS P       ON P.ACT_CODE = A.ACT_CODE
JOIN CLASSIFICATION C ON C.MOVIE_CODE = P.MOVIE_CODE
WHERE C.GEN_CODE = 'DD8'
  AND A.BIRTH_DATE = (
        SELECT MAX(A2.BIRTH_DATE)
        FROM ACTOR_E A2
        JOIN PERFORMS P2       ON P2.ACT_CODE = A2.ACT_CODE
        JOIN CLASSIFICATION C2 ON C2.MOVIE_CODE = P2.MOVIE_CODE
        WHERE C2.GEN_CODE = 'DD8'
);

--Exercise 32

SELECT C.COUNTRY_CODE, C.NAME
FROM COUNTRY C
WHERE NOT EXISTS(SELECT *
                FROM ACTOR_E A
                WHERE A.COUNTRY_CODE = C.COUNTRY_CODE
                AND EXTRACT(YEAR FROM A.BIRTH_DATE) NOT BETWEEN 1900 AND 1999)
AND EXISTS(SELECT *
          FROM ACTOR_E A
          WHERE A.COUNTRY_CODE = C.COUNTRY_CODE)
ORDER BY C.NAME;

--Exercise 33

SELECT A.ACT_CODE, A.NAME
FROM ACTOR_E A
WHERE NOT EXISTS(SELECT *
                 FROM PERFORMS P
                 WHERE P.ACT_CODE = A.ACT_CODE AND P.ROLE NOT LIKE 'Secundario')
AND EXISTS (SELECT *
            FROM PERFORMS P
            WHERE P.ACT_CODE = A.ACT_CODE);

--Exercise 34

-- Actores que aparecen en TODAS las pelis dirigidas por Guy Ritchie
SELECT A.ACT_CODE, A.NAME
FROM ACTOR_E A
WHERE NOT EXISTS (                                  -- No debe existir...
    SELECT *
    FROM MOVIE M
    WHERE M.DIRECTOR LIKE '%Guy Ritchie%'           -- ...ninguna peli de Guy Ritchie
      AND NOT EXISTS (                              -- ...para la que NO exista
          SELECT *                                  -- ...una actuación de ese actor
          FROM PERFORMS P
          WHERE P.ACT_CODE = A.ACT_CODE
            AND P.MOVIE_CODE = M.MOVIE_CODE
      )
)
AND EXISTS (                                        -- Evitar verdad vacía:
    SELECT *                                        -- exigir que Guy Ritchie
    FROM MOVIE M                                    -- tenga al menos 1 peli
    WHERE M.DIRECTOR LIKE '%Guy Ritchie%'
);

--Exercise 35

SELECT A.ACT_CODE, A.NAME
FROM ACCTOR_E A
WHERE NOT EXISTS(SELECT *
                FROM MOVIE M
                WHERE M.DIRECTOR LIKE 'John Steel' AND NOT EXISTS(SELECT *
                                                              FROM PERFORMS P
                                                              WHERE P.MOVIE_CODE = M.MOVIE_CODE AND P.ACT_CODE = A.ACT_CODE))
AND EXISTS (SELECT *
          FROM MOVIE M
          WHERE M.DIRECTOR LIKE 'John Steel');
